apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
spec:
  selector:
    app: api-rest
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 8000
  type: ClusterIP
