apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-worker-deployment
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: shipay.com.br/capacity-type
                  operator: In
                  values:
                    - ondemand
